apiVersion: v1
kind: Service
metadata:
  name: alice-bot-service
  labels:
    app: alice-bot
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: alice-bot